landing_page/urls.py
from django.urls import path, include
from .views import index
from .views import add_status

app_name = "landing_page"

urlpatterns = [
    path("", index, name='index'),
    path("add_status/", add_status, name='add_my_status'),
]

learn_jquery/urls.py
from django.urls import path
from .views import index_jquery

app_name = "learn_jquery"

urlpatterns = [
    path("", index_jquery, name='index_jquery'),
]

story6rian/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landing_page.urls"), name="landing"),
    path('learnjquery/', include("learn_jquery.urls"), name="learnjquery"),  
]

landing_page/models.py
from django.db import models

class MyStatus(models.Model):
    the_status = models.CharField(max_length=300)
    time_uploaded = models.DateTimeField(auto_now_add=True)

learn_jquery/models.py
from django.db import models

# Create your models here.

landing_page/forms.py
from django import forms
from .models import MyStatus

class StatusForm(forms.ModelForm):
    the_status = forms.CharField(
        max_length=300, label= "the_status", 
        widget = forms.Textarea(attrs={
            'title': "post_a_status",
            'name' : "post_a_status",

        })
    )

    class Meta:
        model = MyStatus
        fields = ["the_status"]

landing_page/views.py
from django.shortcuts import render, redirect
from .models import MyStatus
from .forms import StatusForm
# Create your views here.

def index(request):

    all_my_status = MyStatus.objects.all().order_by("time_uploaded")

    a_status_form = StatusForm()
    context = {
        "form" : a_status_form,
        "all_status" : all_my_status
    }

    return render(request, "home.html", context)

def add_status(request):
    
    a_status_form = StatusForm(request.POST or None)
    
    if request.method == "POST":
        if a_status_form.is_valid():
            a_status_form.save()
            return redirect("landing_page:index")
        else:
            a_status_form = StatusForm()

    return redirect("landing_page:index")

learn_jquery/views.py
from django.shortcuts import render

def index_jquery(request):
    return render(request, 'index.html')

landing_page/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>What's Up, Rian?</title>
</head>
<body>


    <div class="container-fluid" style="min-height: 665px;">
        <form action="{% url 'landing_page:add_my_status' %}" method="POST">
            <div>
                {% csrf_token %}
                <h1 class="text-center">
                    Hello, What's Up?<br>
                </h1>
                <div class="text-center">
                    {{ form.the_status }}
                </div>
            </div>

            <div class="text-center">
                <button type="submit" id="submit_post" class="btn btn-primary">Post it!</button>
            </div>        
        </form>    
    </div>
                
    <div class="container-fluid" id="column_status" style="background-color: #FFA69E;">
        <div class="row">
            {% for status in all_status %}
            <div class="col-4">
                <div class="card" style="margin: 15px;">
                    <div class="card-header">
                        <br>
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p>{{ status.the_status }}</p>
                            <footer class="blockquote-footer">{{ status.time_uploaded }}</footer>
                        </blockquote>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    
</body>
</html>

learn_jquery/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'index_jquery.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'index_jquery.js' %}" type="text/javascript"></script>
    <title>Hello JQuery!</title>
    
</head>
<body>
    <div class="container">
        <dl class="accordion">
            <dt class="header" ><a id="first_header" class="title_acc" href="">Aktivitas</a></dt>
            <dd>
                <p class="value">
                    Aktivitas saya saat ini adalah kuliah setiap senin - jumat, menjadi asisten dosen untuk mata kuliah DDP1
                    dan menjalani hobi sebagai pengajar di suatu lembaga bimbel.
                </p>
            </dd>
            <dt class="header"><a class="title_acc" href="">Pengalaman</a></dt>
            <dd>
                <p class="value">
                    Beberapa pengalaman saya antara lain:
                </p>
                <div class="value">
                    <li>
                        Ketua Ekstrakurikuler Musik Modern SMAN 1 Cibungbulang
                    </li>
                    <li>
                        Staff Perlengkapan Educare
                    </li>
                    <li>
                        Staff Syiar Kreatif FUKI Fasilkom UI
                    </li>
                    <li>
                        PJ Penunjang SIWAK-NG 2019
                    </li>
                    <li>
                        Asisten Dosen DDP1
                    </li>
                    <li>
                        Tentor MTK Primagama
                    </li>
                </div>
                
            </dd>
    
            <dt class="header"><a class="title_acc" href="">Penghargaan</a></dt>
            <dd>
                <div class="value">
                    <li>
                        Juara 1 Lomba Band Tingkat SMA se-Kabupaten Bogor
                    </li>
                    <li>
                        Juara 3 Lomba Band Tingkat SMA se-Bogor Barat
                    </li>
                </div>
            </dd>
        </dl>
    
        <div class="text-center">
            <button type="button" class="btn btn-outline-dark" id="button_theme">Change Theme!</button>
        </div>
    </div>

</body>
</html>